"""The dose-sweep generator must make exactly three edits, or refuse to write.

tests/characterization/test_dose_sweep_configs.py asserts the property on the
configs already committed. This asserts it on the code that produces them, so a
regression is caught before it writes 90 files rather than after.

Everything here is local_unit: synthetic config text, a tmp_path destination, no
cluster and no container. The generator is pure text manipulation, so there is
no reason for any of it to need a GPU.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
GENERATOR = REPO_ROOT / "scripts" / "make_dose_sweep.py"

# The three mutable keys plus enough context that a stray edit would show up.
# negsteer_n_designs is 20 here because that is what the benchmark asks for,
# which is what makes dose 20 the two-line case rather than the three-line one.
CONFIG = '''name: "6R8M"

reference_pdb:   "../../../solved/6R8M.pdb"
receptor_chain:  "A"
effector_chain:  "B"

negsteer_n_designs:            20
negsteer_num_seeds:            3
negsteer_diffusion_samples:    5
'''


@pytest.fixture(scope="module")
def gen():
    spec = importlib.util.spec_from_file_location("make_dose_sweep", GENERATOR)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _body(text: str) -> list[str]:
    """Strip the generated header, leaving the copied config body."""
    lines = text.splitlines()
    n = len(CONFIG.splitlines())
    return lines[len(lines) - n:]


# --------------------------------------------------------------------------
# transform
# --------------------------------------------------------------------------

@pytest.mark.local_unit
def test_transform_rewrites_the_three_keys(gen) -> None:
    body = _body(gen.transform(CONFIG, "6R8M", 3))
    assert 'name: "6R8M_n03"' in body
    assert 'reference_pdb:   "../../../benchmarking/unconstrained/6R8M/6R8M.pdb"' in body
    assert "negsteer_n_designs:            3" in body


@pytest.mark.local_unit
def test_transform_changes_nothing_else(gen) -> None:
    """The whole point of the sweep. Anything else moving is a confound."""
    body = _body(gen.transform(CONFIG, "6R8M", 3))
    original = CONFIG.splitlines()
    assert len(body) == len(original)
    changed = [b for a, b in zip(original, body) if a != b]
    assert len(changed) == 3
    for line in changed:
        assert line.startswith(("name:", "reference_pdb:", "negsteer_n_designs:"))


@pytest.mark.local_unit
def test_transform_at_dose_20_changes_only_two_lines(gen) -> None:
    """The benchmark already asks for 20, so that line is already correct."""
    body = _body(gen.transform(CONFIG, "6R8M", 20))
    changed = [b for a, b in zip(CONFIG.splitlines(), body) if a != b]
    assert len(changed) == 2
    assert not any(c.startswith("negsteer_n_designs:") for c in changed)
    assert "negsteer_n_designs:            20" in body


@pytest.mark.local_unit
def test_transform_pads_the_dose_in_the_name(gen) -> None:
    """n03 not n3, so the sweep sorts in dose order rather than lexically."""
    assert 'name: "6R8M_n03"' in gen.transform(CONFIG, "6R8M", 3)
    assert 'name: "6R8M_n50"' in gen.transform(CONFIG, "6R8M", 50)


@pytest.mark.local_unit
def test_transform_prepends_the_provenance_header(gen) -> None:
    out = gen.transform(CONFIG, "6R8M", 10)
    assert out.startswith("# ===")
    head = out[: out.index('name: "')]
    assert "6R8M at 10 set(s)" in head
    assert "GENERATED by scripts/make_dose_sweep.py" in head
    assert "must not be pooled" in head, "the header is what stops these being read as benchmark runs"


@pytest.mark.local_unit
@pytest.mark.parametrize("missing", ["name", "reference_pdb", "negsteer_n_designs"])
def test_transform_refuses_a_config_missing_a_key(gen, missing: str) -> None:
    """A silent no-op edit would produce a config that looks right and is not."""
    text = "\n".join(ln for ln in CONFIG.splitlines() if not ln.startswith(f"{missing}:"))
    with pytest.raises(SystemExit) as exc:
        gen.transform(text + "\n", "6R8M", 3)
    assert missing in str(exc.value)
    assert "did not take" in str(exc.value)


# Both structural guards are reached the same way, through a config that puts a
# value on the line below its key. The patterns use \s*, which spans a newline,
# so the match covers two lines. Which guard fires depends on the replacement:
# reference_pdb keeps its \1 capture (newline included, so the count holds and
# the wrong line moves), while name substitutes a flat string (so a line is lost).

@pytest.mark.local_unit
def test_transform_refuses_when_a_line_it_may_not_touch_moves(gen) -> None:
    text = ('name: "6R8M"\n'
            'negsteer_n_designs:            20\n'
            'reference_pdb:\n'
            '   "../../../solved/6R8M.pdb"\n')
    with pytest.raises(SystemExit) as exc:
        gen.transform(text, "6R8M", 3)
    assert "changed lines it should not" in str(exc.value)
    # The offending line is the unkeyed continuation, not one of the three keys.
    assert '   "../../../benchmarking/unconstrained/6R8M/6R8M.pdb"' in str(exc.value)


@pytest.mark.local_unit
def test_transform_refuses_when_the_line_count_changes(gen) -> None:
    """Here every shifted line happens to start with an allowed key, so the
    stray check passes and only the count guard stands between a collapsed
    config and being written."""
    text = ('name:\n'
            '   "6R8M"\n'
            'negsteer_n_designs:            20\n'
            'reference_pdb:   "../../../solved/6R8M.pdb"\n')
    with pytest.raises(SystemExit) as exc:
        gen.transform(text, "6R8M", 3)
    assert "line count changed" in str(exc.value)


# --------------------------------------------------------------------------
# main
# --------------------------------------------------------------------------

@pytest.fixture
def tree(gen, tmp_path, monkeypatch):
    """A two-target source tree and an empty destination, both under tmp_path."""
    src, dest = tmp_path / "unconstrained", tmp_path / "dose-sweep"
    for target in ("6R8M", "7QPX"):
        d = src / target
        d.mkdir(parents=True)
        (d / "config.yml").write_text(CONFIG.replace('"6R8M"', f'"{target}"'))
    monkeypatch.setattr(gen, "SOURCE", src)
    monkeypatch.setattr(gen, "DEST", dest)
    monkeypatch.setattr(gen, "REPO_ROOT", tmp_path)
    return dest


@pytest.mark.local_unit
def test_main_writes_one_config_per_target_per_dose(gen, tree) -> None:
    assert gen.main(["--doses", "3", "5"]) == 0
    written = sorted(p.relative_to(tree).as_posix() for p in tree.glob("*/*/config.yml"))
    assert written == [
        "n03/6R8M/config.yml", "n03/7QPX/config.yml",
        "n05/6R8M/config.yml", "n05/7QPX/config.yml",
    ]
    assert 'name: "7QPX_n05"' in (tree / "n05" / "7QPX" / "config.yml").read_text()


@pytest.mark.local_unit
def test_main_defaults_to_every_dose(gen, tree) -> None:
    assert gen.main([]) == 0
    assert sorted(p.name for p in tree.iterdir()) == ["n03", "n05", "n10", "n20", "n50"]


@pytest.mark.local_unit
def test_main_dry_run_writes_nothing(gen, tree, capsys) -> None:
    assert gen.main(["--doses", "3", "--dry-run"]) == 0
    assert not tree.exists()
    out = capsys.readouterr().out
    assert "would write" in out
    assert "n03/6R8M/config.yml" in out


@pytest.mark.local_unit
def test_main_reports_the_count_it_wrote(gen, tree, capsys) -> None:
    gen.main(["--doses", "3", "5"])
    assert "wrote 4 configs across 2 doses x 2 targets" in capsys.readouterr().out


@pytest.mark.local_unit
def test_main_fails_loudly_on_an_empty_source_tree(gen, tmp_path, monkeypatch, capsys) -> None:
    """Writing zero configs and exiting 0 would look like success."""
    monkeypatch.setattr(gen, "SOURCE", tmp_path / "nothing-here")
    assert gen.main([]) == 1
    assert "no configs under" in capsys.readouterr().err
