#!/usr/bin/env python3
"""Generate the mutation-set dose sweep from the unconstrained benchmark specs.

The benchmark asks for 20 mutation sets per target. This builds the same 18
targets at several other values, so the dose axis is a within-experiment
contrast rather than the between-target one the README lists as a known limit.

Each generated config is the tracked unconstrained benchmark config with exactly
three lines changed, `name`, `reference_pdb` and `negsteer_n_designs`. Everything
else is copied byte for byte, comments included, so the only thing varying across
the sweep is the dose. The script asserts that, and refuses to write a config
that differs anywhere else.

The reference PDB is not copied. Each config points back at the tracked one under
experiments/benchmarking/unconstrained/, so there is one copy of each structure.

A target can only produce so many distinct sets, and asking for more returns fewer
with a warning. Where that happens the higher-dose runs duplicate the lower-dose
ones and should not be read as having received the dose asked.

Usage:
  python3 scripts/make_dose_sweep.py                 # write the sweep
  python3 scripts/make_dose_sweep.py --dry-run       # show what it would write
  python3 scripts/make_dose_sweep.py --doses 3 5     # a subset
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE = REPO_ROOT / "experiments" / "benchmarking" / "unconstrained"
DEST = REPO_ROOT / "experiments" / "dose-sweep"
DOSES = (3, 5, 10, 20, 50)

HEADER = """# =============================================================================
# Mutation-set dose sweep — {target} at {dose} set(s)
# =============================================================================
# GENERATED by scripts/make_dose_sweep.py. Do not hand-edit; regenerate instead.
#
# This is the tracked unconstrained benchmark config for {target} with three
# lines changed: name, reference_pdb and negsteer_n_designs. Every other value,
# including the steering mode, the seed and the postprocess thresholds, is
# identical to the benchmark, so the dose is the only thing that varies.
#
# NOT a benchmark run. Its numbers belong to the sweep and must not be pooled
# with experiments/benchmarking/.
# =============================================================================

"""


def transform(text: str, target: str, dose: int) -> str:
    """Apply the three edits, and prove nothing else moved."""
    out = re.sub(r'^name:\s*"[^"]*"',
                 f'name: "{target}_n{dose:02d}"', text, count=1, flags=re.M)
    out = re.sub(r'^(reference_pdb:\s*)"[^"]*"',
                 rf'\1"../../../benchmarking/unconstrained/{target}/{target}.pdb"',
                 out, count=1, flags=re.M)
    out = re.sub(r'^(negsteer_n_designs:\s*)\d+',
                 rf'\g<1>{dose}', out, count=1, flags=re.M)

    # Only those three keys may move. At dose 20 only two lines differ, because
    # the benchmark already asks for 20, so assert on WHICH lines changed rather
    # than how many.
    allowed = ("name:", "reference_pdb:", "negsteer_n_designs:")
    changed = [(a, b) for a, b in zip(text.splitlines(), out.splitlines()) if a != b]
    stray = [b for _, b in changed if not b.startswith(allowed)]
    if stray:
        raise SystemExit(
            f"ERROR: {target} at dose {dose} changed lines it should not:\n"
            + "\n".join(f"  {s}" for s in stray))
    if len(text.splitlines()) != len(out.splitlines()):
        raise SystemExit(f"ERROR: {target} line count changed.")

    # And the three must now read what we intended.
    for pattern, what in (
        (rf'^name: "{target}_n{dose:02d}"$', "name"),
        (rf'^reference_pdb:\s+"\.\./\.\./\.\./benchmarking/unconstrained/{target}/{target}\.pdb"$',
         "reference_pdb"),
        (rf'^negsteer_n_designs:\s+{dose}\b', "negsteer_n_designs"),
    ):
        if not re.search(pattern, out, flags=re.M):
            raise SystemExit(f"ERROR: {target} at dose {dose}: {what} did not take.")
    return HEADER.format(target=target, dose=dose) + out


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--doses", type=int, nargs="+", default=list(DOSES))
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args(argv)

    sources = sorted(SOURCE.glob("*/config.yml"))
    if not sources:
        print(f"ERROR: no configs under {SOURCE}", file=sys.stderr)
        return 1

    written = 0
    for dose in args.doses:
        for src in sources:
            target = src.parent.name
            body = transform(src.read_text(), target, dose)
            dest = DEST / f"n{dose:02d}" / target / "config.yml"
            if args.dry_run:
                print(f"would write {dest.relative_to(REPO_ROOT)}")
            else:
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_text(body)
            written += 1

    verb = "would write" if args.dry_run else "wrote"
    print(f"{verb} {written} configs across {len(args.doses)} doses "
          f"x {len(sources)} targets -> {DEST.relative_to(REPO_ROOT)}/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
